'''
Python Programming Automation Assignment : 13

Design automation script which performs following task.

Accept Directory name from user and delete all duplicate files from the specified directory by considering the checksum 
of files. Create one Directory named as Marvellous and inside that directory create log file which maintains all names
of duplicate files which are deleted.Name of that log file should contains the date and time at which that file gets created.
Accept duration in minutes from user and perform task of duplicate file removal after the specific time interval.
Accept Mail id from user and send the attachment of the log file.
Mail body should contains statistics about the operation of duplicate file removal.

Mail body should contains below things :

	Starting time of scanning
	Total number of files scanned
	Total number of duplicate files found

Consider below command line options for the gives script

input:
	   .py   ExistingDir NewDirName  SenderMail-id  Sender-pw   ReceiverMail-id   Time
	   
	   ABC.py   Demo    Demo2        tc@gmail.com	abc123		tom@gmail.com	   5 minutes
	   
	  we have to pass cmd argumets to in above given format		

'''

import sys
import os
import time
import psutil
import shutil
import hashlib
import urllib2
import smtplib
from email.mime.multipart import MIMEMultipart		# below are file attachemet module 
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import schedule


icnt = 0;
i = 0
def help():

	print("input like: .py   ExistingDir NewDirName  SenderMail-id  Sender-pw   ReceiverMail-id   Time");
	print("ABC.py   Demo    Demo2        tc@gmail.com	abc123		tom@gmail.com	   5 minutes");


def mailSender(filename, time):
	
	senderid = sys.argv[3]
	senderpw = sys.argv[4];
	receiverid = sys.argv[5];

	try:
		msg = MIMEMultipart(); 
		msg['From']= senderid;
		msg['To']=receiverid;
		body ="""
		Hello %s
		Here is details of Duplicate files
		which i had 
		
		please check below txt file
		
		this is autogenerated mail
		
		Thanks 
		""" %(receiverid)		
		
		Subject = """
		All Duplicates files Details Logger %s """%(time);
		
		
		msg ["Subject"] = Subject;
		
		msg.attach(MIMEText(body,'plain'));	
	
		fobj = open(filename, 'rb');
		
		prt = MIMEBase('application', 'octet-stream');
	
		prt.set_payload((fobj).read());
		
		encoders.encode_base64(prt);
	
		prt.add_header('Content-Disposition',"attachment; filename=%s"%filename);
	
		msg.attach(prt);
	
		server = smtplib.SMTP_SSL("smtp.gmail.com",465);
	
		server.ehlo();
	
		server.login(senderid, senderpw);
		
		txt = msg.as_string();
	
		server.sendmail(senderid, receiverid, txt);
		
		server.quit();
	
		print("Successfully mail sent....");
	
	except Exception as E:
		print("Exception occured",E);	

def checkSum(filePath):

	fobj = open(filePath,'rb'); # rb is reading mode of filedate in binary format and give it fobj return
	txt = fobj.read();
	
	return hashlib.md5(txt).hexdigest();



def is_connected():
	
	try:
		urllib2.urlopen("http://216.58.192.142",timeout=1);
		return True;
	except urllib2.URLError as err:
		return False;

def ProcessInfo(Ex = sys.argv[1], newD = sys.argv[2]):
	
	global icnt;
	icnt2 = 0;
	if not os.path.exists(Ex):
		print("Given dir not exitst")
		exit();
	
	flag = os.path.exists(newD);
			
	if flag == False:
		os.makedirs(newD);
	else:
		print(newD," is existing");
		print("Enter Another name");
		exit();
		
	filename ="Logfile_%s.txt"%(time.ctime());	
	
	filename = os.path.join(newD, filename); # joinign of path and file
	flname = os.path.join(newD, "DuplicateFileLogs%s.txt"%(time.ctime()));
	
	
	sep = "\n";
	newline = "\n";
	seperator = '-'*50+"\n";
	fobj = open(filename, 'w');
	fobj.write(seperator);
	fobj.write("Running Process on Machine %s \n"%(time.ctime()))
	fobj.write(seperator);
	
	
	dict1 = {}; # emptyy dictionry
	
	for folder, subfolders, filelist in os.walk(Ex):
		
		for filen in filelist:
			filen = os.path.join(folder, filen);
						
			checksum = checkSum(filen);
			
			if  not checksum in dict1:
				dict1[checksum]=[checksum];
			else:			
				fobj.write("FileName   ::%s"%filen);
				fobj.write(sep);
				fobj.write("FileChksum ::%s"%checksum);
				fobj.write(sep);
				fobj.write("CreatedTime::%s"%time.ctime(os.path.getctime(filen)));
				fobj.write(sep+newline)
				icnt2 = icnt2 + 1;				
				os.remove(filen);
				icnt = icnt2;
	
	if icnt2 > 0:
		fobj.write(seperator);
	
	fobj.write("Total Duplicate files ares : %s"%icnt2);		
	fobj.close();
	
	if icnt > 0:
		print("All files copy successfullyy..");
	else:
		print("No Duplicate file foundes");
			
	
	try:			
		connected = is_connected();
		if connected:	

			if os.path.isfile(filename):
				mailSender(filename, time.ctime());
				shutil.rmtree(newD)					
	except Exception as e:
		print("Exceptionn occured",e);
	
		
def main():
	
	print("Applicatioon Name: ",sys.argv[0]);
	
	starttime = time.time();
	schedule.every(int(str(sys.argv[6]))).minutes.do(ProcessInfo);
	print("Total Scanning time is: %s", (time.time() - starttime));

	while 1:
		print(time.ctime());
		schedule.run_pending();
		time.sleep(1);
	

if __name__ == "__main__":
	main();
	
	
